name = "yogiwebsite"
# Removed deprecated fields (route, account_id, type, zone_id, site.entry-point) and removed the [site] section so that wrangler dev does not serve static assets.
# (In dev mode, the minimal Worker (src/index.js) returns a fallback message.)
main = "src/index.js"

# Cloudflare Pages configuration
[build]
command = "npm run build"
output_dir = "dist"

# Wrangler site configuration
[site]
bucket = "./dist"

# Pages configuration
[pages]
pages_build_output_dir = "dist" 